#!/bin/bash
#här kommer jag att göra ett openvpn script
#
# Detta är under konstruktion vänligen rör ej!
#
#
#####################################################################################################################
#                                                                                                                   #
#                         This script is written by Johan aka Saint, admin of Webbh4tt                              #
#  This program is open source; you can redistribute it and/or modify it under the terms of the GNU General Public  #
#                       The author bears no responsibility for malicious or illegal use.                            #
#                                                                                                                   #
#                                                                                                                   #
#####################################################################################################################

#########################################################################################
#                                           known bugs                                  #
#                                           None so far                                 #
#                             Please report bugs to info@webbhatt.com                   #
#########################################################################################

# ~~~~~~~~~~ Environment Setup ~~~~~~~~~~ #
. ./environment
# ~~~~~~~~~~ Environment Setup ~~~~~~~~~~ #

#################################Start script and validation####################################
if [[ $EUID -ne 0 ]]; then
echo -e "${WARNING}Script must be run as root!${END}"
exit 1
else
apt-get install pptpd

mknod /dev/ppp c 108 0
echo 1 > /proc/sys/net/ipv4/ip_forward
echo "mknod /dev/ppp c 108 0" >> /etc/rc.local
echo "echo 1 > /proc/sys/net/ipv4/ip_forward" >> /etc/rc.local
#ska skapa frågesats för följande värden
echo "localip 172.16.36.1" >> /etc/pptpd.conf
#ska skapa frågesats för följande värden
echo "remoteip 172.16.36.2-254" >> /etc/pptpd.conf


pass=`openssl rand 6 -base64`
if [ "$1" != "" ]
then pass=$1
fi

echo "vpn pptpd ${pass} *" >> /etc/ppp/chap-secrets

iptables -t nat -A POSTROUTING -s 172.16.36.0/24 -j SNAT --to-source `ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk 'NR==1 { print $1}'`
iptables -A FORWARD -p tcp --syn -s 172.16.36.0/24 -j TCPMSS --set-mss 1356
service iptables save

chkconfig iptables on
chkconfig pptpd on

service iptables start
service pptpd start

echo "VPN service is installed, your VPN username is vpn, VPN password is ${pass}"
